
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: alertspolicies.nr.k8s.newrelic.com
spec:
  group: nr.k8s.newrelic.com
  names:
    kind: AlertsPolicy
    listKind: AlertsPolicyList
    plural: alertspolicies
    singular: alertspolicy
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: AlertsPolicy is the Schema for the policies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AlertsPolicySpec defines the desired state of AlertsPolicy
          properties:
            account_id:
              type: integer
            api_key:
              type: string
            api_key_secret:
              properties:
                key_name:
                  type: string
                name:
                  type: string
                namespace:
                  type: string
              type: object
            channel_ids:
              items:
                type: integer
              type: array
            conditions:
              items:
                description: AlertsPolicyCondition defined the conditions contained
                  within an AlertsPolicy
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                  spec:
                    properties:
                      account_id:
                        type: integer
                      api_key:
                        type: string
                      api_key_secret:
                        properties:
                          key_name:
                            type: string
                          name:
                            type: string
                          namespace:
                            type: string
                        type: object
                      apm_terms:
                        items:
                          description: AlertConditionTerm represents the terms of
                            a New Relic alert condition.
                          properties:
                            duration:
                              type: string
                            operator:
                              type: string
                            priority:
                              type: string
                            threshold:
                              type: string
                            time_function:
                              type: string
                            violation_close_timer:
                              type: integer
                          required:
                          - threshold
                          type: object
                        type: array
                      baseline_direction:
                        description: NrqlBaselineDirection
                        type: string
                      condition_scope:
                        type: string
                      description:
                        type: string
                      enabled:
                        type: boolean
                      entities:
                        items:
                          type: string
                        type: array
                      existing_policy_id:
                        type: string
                      expected_groups:
                        type: integer
                      expiration:
                        description: AlertsNrqlConditionExpiration Settings for how
                          violations are opened or closed when a signal expires.
                        properties:
                          closeViolationsOnExpiration:
                            type: boolean
                          expirationDuration:
                            type: integer
                          openViolationOnExpiration:
                            type: boolean
                        type: object
                      gc_metric:
                        type: string
                      id:
                        type: integer
                      ignore_overlap:
                        type: boolean
                      metric:
                        type: string
                      name:
                        type: string
                      nrql:
                        description: NrqlConditionQuery represents the NRQL query
                          object returned in a NerdGraph response object.
                        properties:
                          evaluationOffset:
                            type: integer
                          query:
                            type: string
                        type: object
                      region:
                        type: string
                      runbook_url:
                        type: string
                      signal:
                        description: AlertsNrqlConditionSignal - Configuration that
                          defines the signal that the NRQL condition will use to evaluate.
                        properties:
                          aggregation_window:
                            type: integer
                          evaluation_offset:
                            type: integer
                          fill_option:
                            description: AlertsFillOption - The available fill options.
                            type: string
                          fill_value:
                            type: string
                        type: object
                      terms:
                        items:
                          description: AlertsNrqlConditionTerm represents the terms
                            of a New Relic alert condition.
                          properties:
                            operator:
                              description: AlertsNRQLConditionTermsOperator - Operator
                                used to compare against the threshold for NrqlConditions.
                              type: string
                            priority:
                              description: NrqlConditionPriority specifies the priority
                                for alert condition terms.
                              type: string
                            threshold:
                              type: string
                            threshold_duration:
                              type: integer
                            threshold_occurrences:
                              description: ThresholdOccurrence specifies the threshold
                                occurrence for NRQL alert condition terms.
                              type: string
                          type: object
                        type: array
                      type:
                        description: NrqlConditionType specifies the type of NRQL
                          alert condition.
                        type: string
                      user_defined:
                        description: ConditionUserDefined represents user defined
                          metrics for the New Relic alert condition.
                        properties:
                          metric:
                            type: string
                          value_function:
                            description: ValueFunctionType specifies the value function
                              to be used for returning custom metric data.
                            type: string
                        type: object
                      valueFunction:
                        description: NrqlConditionValueFunction specifies the value
                          function of NRQL alert condition.
                        type: string
                      violation_close_timer:
                        type: integer
                      violationTimeLimit:
                        description: NrqlConditionViolationTimeLimit specifies the
                          value function of NRQL alert condition.
                        type: string
                    required:
                    - enabled
                    type: object
                type: object
              type: array
            incidentPreference:
              type: string
            name:
              type: string
            region:
              type: string
          required:
          - name
          - region
          type: object
        status:
          description: AlertsPolicyStatus defines the observed state of AlertsPolicy
          properties:
            applied_spec:
              description: AlertsPolicySpec defines the desired state of AlertsPolicy
              properties:
                account_id:
                  type: integer
                api_key:
                  type: string
                api_key_secret:
                  properties:
                    key_name:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                channel_ids:
                  items:
                    type: integer
                  type: array
                conditions:
                  items:
                    description: AlertsPolicyCondition defined the conditions contained
                      within an AlertsPolicy
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      spec:
                        properties:
                          account_id:
                            type: integer
                          api_key:
                            type: string
                          api_key_secret:
                            properties:
                              key_name:
                                type: string
                              name:
                                type: string
                              namespace:
                                type: string
                            type: object
                          apm_terms:
                            items:
                              description: AlertConditionTerm represents the terms
                                of a New Relic alert condition.
                              properties:
                                duration:
                                  type: string
                                operator:
                                  type: string
                                priority:
                                  type: string
                                threshold:
                                  type: string
                                time_function:
                                  type: string
                                violation_close_timer:
                                  type: integer
                              required:
                              - threshold
                              type: object
                            type: array
                          baseline_direction:
                            description: NrqlBaselineDirection
                            type: string
                          condition_scope:
                            type: string
                          description:
                            type: string
                          enabled:
                            type: boolean
                          entities:
                            items:
                              type: string
                            type: array
                          existing_policy_id:
                            type: string
                          expected_groups:
                            type: integer
                          expiration:
                            description: AlertsNrqlConditionExpiration Settings for
                              how violations are opened or closed when a signal expires.
                            properties:
                              closeViolationsOnExpiration:
                                type: boolean
                              expirationDuration:
                                type: integer
                              openViolationOnExpiration:
                                type: boolean
                            type: object
                          gc_metric:
                            type: string
                          id:
                            type: integer
                          ignore_overlap:
                            type: boolean
                          metric:
                            type: string
                          name:
                            type: string
                          nrql:
                            description: NrqlConditionQuery represents the NRQL query
                              object returned in a NerdGraph response object.
                            properties:
                              evaluationOffset:
                                type: integer
                              query:
                                type: string
                            type: object
                          region:
                            type: string
                          runbook_url:
                            type: string
                          signal:
                            description: AlertsNrqlConditionSignal - Configuration
                              that defines the signal that the NRQL condition will
                              use to evaluate.
                            properties:
                              aggregation_window:
                                type: integer
                              evaluation_offset:
                                type: integer
                              fill_option:
                                description: AlertsFillOption - The available fill
                                  options.
                                type: string
                              fill_value:
                                type: string
                            type: object
                          terms:
                            items:
                              description: AlertsNrqlConditionTerm represents the
                                terms of a New Relic alert condition.
                              properties:
                                operator:
                                  description: AlertsNRQLConditionTermsOperator -
                                    Operator used to compare against the threshold
                                    for NrqlConditions.
                                  type: string
                                priority:
                                  description: NrqlConditionPriority specifies the
                                    priority for alert condition terms.
                                  type: string
                                threshold:
                                  type: string
                                threshold_duration:
                                  type: integer
                                threshold_occurrences:
                                  description: ThresholdOccurrence specifies the threshold
                                    occurrence for NRQL alert condition terms.
                                  type: string
                              type: object
                            type: array
                          type:
                            description: NrqlConditionType specifies the type of NRQL
                              alert condition.
                            type: string
                          user_defined:
                            description: ConditionUserDefined represents user defined
                              metrics for the New Relic alert condition.
                            properties:
                              metric:
                                type: string
                              value_function:
                                description: ValueFunctionType specifies the value
                                  function to be used for returning custom metric
                                  data.
                                type: string
                            type: object
                          valueFunction:
                            description: NrqlConditionValueFunction specifies the
                              value function of NRQL alert condition.
                            type: string
                          violation_close_timer:
                            type: integer
                          violationTimeLimit:
                            description: NrqlConditionViolationTimeLimit specifies
                              the value function of NRQL alert condition.
                            type: string
                        required:
                        - enabled
                        type: object
                    type: object
                  type: array
                incidentPreference:
                  type: string
                name:
                  type: string
                region:
                  type: string
              required:
              - name
              - region
              type: object
            policy_id:
              type: string
          required:
          - applied_spec
          - policy_id
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
