
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: alertsnrqlconditions.nr.k8s.newrelic.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.created
    name: Created
    type: boolean
  group: nr.k8s.newrelic.com
  names:
    kind: AlertsNrqlCondition
    listKind: AlertsNrqlConditionList
    plural: alertsnrqlconditions
    singular: alertsnrqlcondition
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: AlertsNrqlCondition is the Schema for the alertsnrqlconditions API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AlertsNrqlConditionSpec defines the desired state of AlertsNrqlCondition
          properties:
            account_id:
              type: integer
            api_key:
              type: string
            api_key_secret:
              properties:
                key_name:
                  type: string
                name:
                  type: string
                namespace:
                  type: string
              type: object
            apm_terms:
              items:
                description: AlertConditionTerm represents the terms of a New Relic alert condition.
                properties:
                  duration:
                    type: string
                  operator:
                    type: string
                  priority:
                    type: string
                  threshold:
                    type: string
                  time_function:
                    type: string
                  violation_close_timer:
                    type: integer
                required:
                - threshold
                type: object
              type: array
            description:
              type: string
            enabled:
              type: boolean
            existing_policy_id:
              type: string
            expected_groups:
              type: integer
            id:
              type: integer
            ignore_overlap:
              type: boolean
            name:
              type: string
            nrql:
              description: NrqlConditionQuery represents the NRQL query object returned in a NerdGraph response object.
              properties:
                evaluationOffset:
                  type: integer
                query:
                  type: string
              type: object
            region:
              type: string
            runbook_url:
              type: string
            terms:
              items:
                description: AlertsNrqlConditionTerm represents the terms of a New Relic alert condition.
                properties:
                  operator:
                    description: NrqlConditionOperator specifies the operator for alert condition terms.
                    type: string
                  priority:
                    description: NrqlConditionPriority specifies the priority for alert condition terms.
                    type: string
                  threshold:
                    type: string
                  threshold_duration:
                    type: integer
                  threshold_occurrences:
                    description: ThresholdOccurrence specifies the threshold occurrence for NRQL alert condition terms.
                    type: string
                type: object
              type: array
            type:
              description: NrqlConditionType specifies the type of NRQL alert condition.
              type: string
            valueFunction:
              description: NrqlConditionValueFunction specifies the value function of NRQL alert condition.
              type: string
            violationTimeLimit:
              description: NrqlConditionViolationTimeLimit specifies the value function of NRQL alert condition.
              type: string
          required:
          - enabled
          type: object
        status:
          description: AlertsNrqlConditionStatus defines the observed state of AlertsNrqlCondition
          properties:
            applied_spec:
              description: AlertsNrqlConditionSpec defines the desired state of AlertsNrqlCondition
              properties:
                account_id:
                  type: integer
                api_key:
                  type: string
                api_key_secret:
                  properties:
                    key_name:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                apm_terms:
                  items:
                    description: AlertConditionTerm represents the terms of a New Relic alert condition.
                    properties:
                      duration:
                        type: string
                      operator:
                        type: string
                      priority:
                        type: string
                      threshold:
                        type: string
                      time_function:
                        type: string
                      violation_close_timer:
                        type: integer
                    required:
                    - threshold
                    type: object
                  type: array
                description:
                  type: string
                enabled:
                  type: boolean
                existing_policy_id:
                  type: string
                expected_groups:
                  type: integer
                id:
                  type: integer
                ignore_overlap:
                  type: boolean
                name:
                  type: string
                nrql:
                  description: NrqlConditionQuery represents the NRQL query object returned in a NerdGraph response object.
                  properties:
                    evaluationOffset:
                      type: integer
                    query:
                      type: string
                  type: object
                region:
                  type: string
                runbook_url:
                  type: string
                terms:
                  items:
                    description: AlertsNrqlConditionTerm represents the terms of a New Relic alert condition.
                    properties:
                      operator:
                        description: NrqlConditionOperator specifies the operator for alert condition terms.
                        type: string
                      priority:
                        description: NrqlConditionPriority specifies the priority for alert condition terms.
                        type: string
                      threshold:
                        type: string
                      threshold_duration:
                        type: integer
                      threshold_occurrences:
                        description: ThresholdOccurrence specifies the threshold occurrence for NRQL alert condition terms.
                        type: string
                    type: object
                  type: array
                type:
                  description: NrqlConditionType specifies the type of NRQL alert condition.
                  type: string
                valueFunction:
                  description: NrqlConditionValueFunction specifies the value function of NRQL alert condition.
                  type: string
                violationTimeLimit:
                  description: NrqlConditionViolationTimeLimit specifies the value function of NRQL alert condition.
                  type: string
              required:
              - enabled
              type: object
            condition_id:
              type: string
          required:
          - applied_spec
          - condition_id
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
